# 20. Tensor Basics - Part One

### load modules

In [2]:
import torch
import numpy as np

### check torch version

In [3]:
torch.__version__

'1.10.1+cu102'

### torch.from_numpy VS. torch.as_tensor

In [4]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


#### torch.from_numpy

In [5]:
x = torch.from_numpy(arr)
print(type(x))
print(x.dtype)

<class 'torch.Tensor'>
torch.int64


#### torch.as_tensor

In [6]:
y = torch.as_tensor(arr)
print(type(y))
print(y.dtype)

<class 'torch.Tensor'>
torch.int64


In [7]:
arr2d = np.arange(0.0, 12.0)

In [8]:
arr2d = arr2d.reshape(4,3)

In [9]:
x2 = torch.from_numpy(arr2d)
print(x2)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)


In [10]:
arr

array([1, 2, 3, 4, 5])

In [11]:
x

tensor([1, 2, 3, 4, 5])

In [12]:
arr[0] = 99 #change first element to 99

In [13]:
arr

array([99,  2,  3,  4,  5])

In [14]:
my_arr = np.arange(0, 10)
print(my_arr)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
my_tensor = torch.tensor(my_arr)
print(my_tensor)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [16]:
my_other_tensor = torch.from_numpy(my_arr)
print(my_other_tensor)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [17]:
my_arr[0] = 9999
print(my_arr)
print(my_tensor) #tensor -> doesn't change
print(my_other_tensor) #from_numpy -> changed

[9999    1    2    3    4    5    6    7    8    9]
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])


# 21. Tensor Basics - Part Two

In [19]:
new_arr = np.array([1,2,3])

In [20]:
new_arr.dtype

dtype('int64')

In [21]:
my_tensor_t = torch.tensor(new_arr)
print(my_tensor_t)

tensor([1, 2, 3])


In [22]:
my_tensor_T = torch.Tensor(new_arr) #.Tensor -> create it as a float
print(my_tensor_T)

tensor([1., 2., 3.])


In [23]:
my_tensor_F = torch.FloatTensor(new_arr)
print(my_tensor_F.dtype)

torch.float32


### torch.empty & torch.zeros & torch.ones

In [24]:
torch.empty(4,3) 

tensor([[-3.7805e+18,  4.5848e-41, -3.7805e+18],
        [ 4.5848e-41,  4.4842e-44,  0.0000e+00],
        [ 1.1210e-43,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [25]:
torch.zeros(4,3) # if you want to integer -> dtype = torch.int32 / torch.int64

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [26]:
torch.zeros(4,3, dtype = torch.int32) # if you want to integer -> dtype = torch.int32 / torch.int64

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [27]:
torch.ones(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [28]:
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [29]:
torch.linspace(0,18,12).reshape(3,4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [30]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [31]:
my_tensor = torch.tensor([1,2,3])
my_tensor.dtype #torch.int64

torch.int64

In [32]:
my_tensor.type(torch.int32)
print(my_tensor.dtype)

torch.int64


In [33]:
torch.rand(4,3)

tensor([[0.6946, 0.6809, 0.1132],
        [0.5540, 0.6414, 0.0210],
        [0.9997, 0.9405, 0.6646],
        [0.1003, 0.8259, 0.3252]])

In [34]:
torch.randn(4,3)

tensor([[ 0.6502, -0.5077,  0.4147],
        [ 1.3037,  0.8713,  0.6594],
        [ 0.6373,  0.9533, -1.9989],
        [-0.1553,  0.9923, -0.3344]])

In [35]:
torch.randint(low=0, high=10, size=(5,5)) #high - exclusive

tensor([[5, 7, 4, 8, 7],
        [4, 2, 9, 4, 8],
        [0, 0, 6, 4, 9],
        [5, 0, 2, 0, 2],
        [0, 5, 1, 4, 2]])

In [36]:
x = torch.zeros(2,5)
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [37]:
x.shape

torch.Size([2, 5])

In [38]:
torch.rand_like(x) #produce a shape of rand function + automatic parameter of 

tensor([[0.0966, 0.4248, 0.4394, 0.1927, 0.1755],
        [0.9259, 0.8683, 0.5268, 0.9104, 0.8672]])

In [39]:
torch.randn_like(x) #uniform stand

tensor([[ 0.0623,  0.8086, -0.0912, -0.1254, -1.7693],
        [ 1.0398, -0.2730,  0.5157, -0.8293, -0.4375]])

In [40]:
torch.randint_like(x, low=0, high=11)

tensor([[ 3.,  5.,  8., 10.,  8.],
        [ 1.,  3.,  5.,  2.,  7.]])

In [41]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [42]:
torch.rand(2,3) #if you do not set manual_seed -> torch.rand() produce different outcomes at each time

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])