# 22. Tensor Operations - Part One

### load modules

In [1]:
import torch
import numpy as np

### torch.arange & .reshape

In [3]:
x = torch.arange(6).reshape(3,2)
print(x)

tensor([[0, 1],
        [2, 3],
        [4, 5]])


In [7]:
x[1,1] #tensor(3)
type(x[1,1]) #torch.Tensor
x[:,1] #tensor([1,3,5])
x[:,1:] 
#tensor([[1],
#        [3],
#        [5]])

tensor([[1],
        [3],
        [5]])

### torch.arange & .view

In [8]:
x = torch.arange(10)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [10]:
x.view(2,5) #same value, but as 2x5 size

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

### torch.arange -> torch.Size([10]) (even) -> x.view(2, -1)

In [13]:
x = torch.arange(10)
print(x) # tensor([0,1,2,3,4,5,6,7,8,9])
print(x.shape) #torch.Size([10])

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.Size([10])


In [14]:
# INFER what the 2nd dimension
x.view(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

### torch.arange -> torch.Size([11]) (odd) -> x.view(2, -1) error

In [16]:
x = torch.arange(11)
print(x) # tensor([0,1,2,3,4,5,6,7,8,9,10])
print(x.shape) #torch.Size([11])

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
torch.Size([11])


In [17]:
# INFER what the 2nd dimension
x.view(2,-1)


##error since shape '[2, -1]' is invalid for input of size 11

RuntimeError: shape '[2, -1]' is invalid for input of size 11

### torch.add(a,b)

In [19]:
a = torch.tensor([1., 2., 3.])
print(a)
print(a.dtype)

tensor([1., 2., 3.])
torch.float32


In [20]:
b = torch.tensor([4., 5., 6])
print(b)
print(b.dtype)

tensor([4., 5., 6.])
torch.float32


In [21]:
a + b #same thing with torch.add(a,b)

tensor([5., 7., 9.])

In [22]:
torch.add(a,b)

tensor([5., 7., 9.])

### a.mul()

In [23]:
a.mul(b) #tensor([4., 10., 18.])

tensor([ 4., 10., 18.])

In [24]:
# dot product 
a.dot(b) #tensor(32.)

tensor(32.)

# 23. Tensor Operations - Part Two

### a @ b

In [29]:
a = torch.tensor([[0,2,4],[1,3,5]])
print(a)
print(a.shape)

tensor([[0, 2, 4],
        [1, 3, 5]])
torch.Size([2, 3])


In [30]:
b = torch.tensor([[6,7], [8,9], [10,11]])
print(b)
print(b.shape)

tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])
torch.Size([3, 2])


In [31]:
torch.mm(a,b)

tensor([[56, 62],
        [80, 89]])

In [32]:
a @ b

tensor([[56, 62],
        [80, 89]])

### L2 or Euclidian Norm

#### example 1

In [33]:
x = torch.tensor([2., 3., 4., 5.])
print(x)

tensor([2., 3., 4., 5.])


In [34]:
x.norm()

tensor(7.3485)

In [36]:
x.numel() #number of elements

4

In [37]:
len(x)

4

#### example 2

In [38]:
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [40]:
len(a)b #number of rows

2

In [41]:
a.numel() #number of elements

6