# 1. Perform standard imports
Import Torch and NumPy

In [1]:
# CODE HERE
import torch
import numpy as np

# 2. Set the random seed for NumPy and PyTorch both to "42"
This allows us to share the same "random" results.

In [2]:
# CODE HERE
np.random.seed(42)
torch.manual_seed(42);

# 3. Create a NumPy array called "arr" that contains 6 random integers between 0 (inclusive) and 5 (exclusive)

In [3]:
# CODE HERE
arr = np.random.randint(0,5,6)
print(arr)

[3 4 2 4 4 1]


# 4. Create a tensor "x" from the array above

In [4]:
# CODE HERE
x = torch.from_numpy(arr)
print(x)

tensor([3, 4, 2, 4, 4, 1])


# 5. Chage the dtype of x from 'int32' to 'int64'
Note: 'int64' is also called 'LongTensor'

In [5]:
# CODE HERE
x = x.type(torch.int64)
print(x)
print(x.type())
print(x.dtype)

tensor([3, 4, 2, 4, 4, 1])
torch.LongTensor
torch.int64


# 6. Reshape x into a 3x2 tensor
There are several ways to do this.

In [6]:
# CODE HERE
x = x.reshape(3,2)

# 7. Return the right-hand column of tensor x

In [7]:
# CODE HERE
print(x)
print(x[:, 1:])

tensor([[3, 4],
        [2, 4],
        [4, 1]])
tensor([[4],
        [4],
        [1]])


# 8. Without changing x, return a tensor of square values of x
There are several ways to do this.

In [8]:
# CODE HERE
x ** 2 #x * x

tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])

# 9. Create a tensor "y" with the same number of elements as x, that can be matrix-multipled with x
Uwe PyTorch directly (not NumPy) to create a tensor of random integers between 0 (inclusive) and 5 (exclulsive).
Think about what shape it should have to permit matrix multiplication.

In [10]:
# CODE HERE
y = torch.randint(0,5,(2,3))
y

tensor([[2, 2, 1],
        [4, 1, 0]])

# 10. Find the matrix product of x and y

In [11]:
# CODE HERE
x.mm(y)

tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])